### PR TITLE
optimizations branch is no more

### PR DESCRIPTION
**Pull request by mr-c**
@josiahseaman is there a docker container for https://github.com/graph-genome/component_segmentation yet?

### CODE REVIEW

**Comment by josiahseaman** [comment]
Sorry I didn't know the answer to this question. Do you still need an answer or is it resolved now?

**Comment by mr-c** [comment]
> @josiahseaman is there a docker container for https://github.com/graph-genome/component_segmentation yet?

For the CWL description, we had been making our own docker container for `component_segmentation`. Does that tool have a conda or Debian package and therefore a container on quay.io made by biocontainers.pro?

**Comment by josiahseaman** [comment]
I don't think there's a containerization of component_segmentation. The
closest is the work that I did to ensure that component segmentation could
be pip installed. It's now listed on PyPI here:
https://pypi.org/project/component-segmentation/  How easy is it to package
it further from that point?

**Comment by mr-c** [comment]
> How easy is it to package it further from that point?

Much easier!

You can request a bioconda packaging at https://github.com/bioconda/bioconda-recipes/issues or do it yourself by following the directions at https://bioconda.github.io/contributor/index.html

For Debian you can request packaging via email or the `reportbug` tool as documented at https://www.debian.org/devel/wnpp/#l1

**Pull request merged**
