### PR TITLE
Fix schema.rdf -> schemaorg-current-http.rdf

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Comment by tetron** [comment]
Maybe this should specify a particular version: https://schema.org/version/9.0/schemaorg-current-http.rdf

**Comment by mr-c** [comment]
I opened https://github.com/schemaorg/schemaorg/issues/2683 to complain about the link breakage upstream

**Comment by mr-c** [comment]
@tetron FYI, `The base branch requires all commits to be signed. `

**Comment by mr-c** [comment]
@tetron Can you sign your commits and force push so I can merge this PR? Thanks!

**Pull request merged**
