### PR TITLE
Create lofreq_call.cwl

### PR DESCRIPTION
**Pull request by cjuigne**

### CODE REVIEW

**Comment by mr-c** [comment]
@hellymac Do you want me to fix and merge this?

**Comment by cjuigne** [comment]
I just found an issue, I will fix it in few minutes!

**Comment by mr-c** [comment]
@hellymac Fwew, glad to hear it. Thought my neglect had scared you away!

**Comment by cjuigne** [comment]
Haha no ! Don't worry, I just updated the good file!

**Comment by mr-c** [comment]
Thanks! I found VCF: http://edamontology.org/format_3016

**Comment by cjuigne** [comment]
Great, thank you!

**Comment by cjuigne** [comment]
It doesn't work anymore, I'm looking for the problem

**Comment by cjuigne** [comment]
Ok sorry, no problem it was underscores ;)

**Pull request merged**
